### ISSUE TITLE
Issue with Add More Items

### ISSUE THREAD

**Issue by earbor-ai** [AdityaRawat96/BoxSizeCalculator#1]
Hi,

Can you please let me know if there is an issue with Add Item? ADD More is not working on the items as well as  box types. 

![Screenshot 2022-09-20 231751](https://user-images.githubusercontent.com/98798986/191413348-0652bbfb-d4cc-47ae-a610-eee109c48df7.png)

**Comment by AdityaRawat96** [comment]
Hey,
I have resolved the issue now. Thanks for reporting.

**Comment by earbor-ai** [comment]
Hi Aditya,

 

We found an issue with the app. Can you please let me know.. Here is our example.. we pack this in 18x14x8 box but you are app is giving us 36x24x12.. Can you please let me know what we are doing wrong? Thanks for your help in advance.

 

Here are the boxes we have: all are in inches

18x7x7

24x9x9

18x14x8

36x24x12

36x24x6

8x8x4

 

Here are the SKU’s we have with sizes and quantities..

	

ProductCode

Line Quantity

Length

Width

Height

Weight


211ACU9701_POR_O/S

2

4.5

2

3.5

0.17


221ACU5501_SUNS_L

1

17.5

7

7

2.6


221ACU5501_TRRS_M

1

15.5

7

7

2

 

 

 

 

Thanks

 

Ram Patibandla

CTO – eArbor LLP/ Seedolabs Pvt Ltd.

+91 9494943394/ +1 (847)986-5808
